torch常见操作示例

In [2]:
import numpy as np
import torch
import torch.nn as nn

（一）张量的创建

In [24]:
a=torch.tensor(4)
b=torch.tensor([3,4])
c=torch.tensor([4,5],dtype=int)
print(a)
print(b)
print(c)

tensor(4)
tensor([3, 4])
tensor([4, 5])


In [43]:
print(torch.zeros(3,3))
print(torch.ones(3,3))
print(torch.eye(3,2))
print(torch.empty(3,2,2))
print(torch.full((3,4),4.37))
print(torch.arange(1,8,1))
print(torch.linspace(1,8,9))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
tensor([[4.3700, 4.3700, 4.3700, 4.3700],
        [4.3700, 4.3700, 4.3700, 4.3700],
        [4.3700, 4.3700, 4.3700, 4.3700]])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1.0000, 1.8750, 2.7500, 3.6250, 4.5000, 5.3750, 6.2500, 7.1250, 8.0000])


from_numpy与as_tensor会将np数据与torch数据内容共享，改变一个另一个自动改变。

In [38]:
a_np=np.array([[1,2],[3,4]])
a_tc=torch.from_numpy(a_np)
print(a_np)
print(a_tc)
a_np[1,1]=-4
print(a_tc)

b=torch.as_tensor([1,2,3])
print(b)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[ 1,  2],
        [ 3, -4]], dtype=torch.int32)
tensor([1, 2, 3])


随机数

In [61]:
print(torch.rand(2,4,2))
print(torch.randn(2,4))
print(torch.normal(mean=torch.arange(0,30.0,5),std=torch.tensor(3.0)))
print(torch.randperm(8))

tensor([[[0.4599, 0.5329],
         [0.5190, 0.1544],
         [0.9084, 0.5454],
         [0.2667, 0.7096]],

        [[0.6792, 0.8754],
         [0.4951, 0.0940],
         [0.7127, 0.9170],
         [0.1040, 0.5811]]])
tensor([[-1.9252,  0.4133, -0.4730,  0.3334],
        [-0.1812, -0.2681,  0.5141,  0.7564]])
tensor([-1.7130,  5.3427,  8.0321, 16.5173, 21.1972, 24.0742])
tensor([0, 6, 5, 3, 2, 7, 1, 4])


（二）张量的类型与转换

In [9]:
print(torch.FloatTensor(2,3).type()) #构建一个2*3 Float类型的张量
print(torch.DoubleTensor(2,3).type()) #构建一个2*3 Double类型的张量
print(torch.HalfTensor (2,3).type()) #构建一个2*3 HalfTenso类型的张量
print(torch.ByteTensor(2,3).type()) #构建一个2*3 Byte类型的张量
print(torch.CharTensor(2,3).type()) #构建一个2*3 Char类型的张量
print(torch.ShortTensor(2,3).type()) #构建一个2*3 Short类型的张量
print(torch.IntTensor(2,3).type()) #构建一个2*3 Int类型的张量
print(torch.LongTensor(2,3).type()) #构建一个2*3 Long类型的张量

torch.FloatTensor
torch.DoubleTensor
torch.HalfTensor
torch.ByteTensor
torch.CharTensor
torch.ShortTensor
torch.IntTensor
torch.LongTensor
torch.LongTensor
torch.FloatTensor


In [13]:
a=torch.tensor([1,2])
print(a.type())
b=torch.randn(2, 2)
print(b.type())
a2=a.float()
print(a2.type())

torch.LongTensor
torch.FloatTensor
torch.FloatTensor


（三）张量的操作与运算

小数处理

In [74]:
a=torch.randn(2,3)
print(a)
print(a.trunc())
print(a.frac())
#还有round,ceil,floor函数

tensor([[-0.4362,  0.1993,  1.2681],
        [-0.2199, -0.4661, -0.1924]])
tensor([[-0., 0., 1.],
        [-0., -0., -0.]])
tensor([[-0.4362,  0.1993,  0.2681],
        [-0.2199, -0.4661, -0.1924]])


_后缀会更新tensor对象的值

In [82]:
a=torch.tensor([[1,3],[2,4]])
print(a)
print(torch.pow(a,2))
print(a.pow(2))
print(a)
print(a.pow_(2))
print(a)

tensor([[1, 3],
        [2, 4]])
tensor([[ 1,  9],
        [ 4, 16]])
tensor([[ 1,  9],
        [ 4, 16]])
tensor([[1, 3],
        [2, 4]])
tensor([[ 1,  9],
        [ 4, 16]])
tensor([[ 1,  9],
        [ 4, 16]])


比较大小

In [127]:
a=torch.tensor([[1,3],[2,4]])
b=torch.tensor([[1,2],[3,4]])
print(torch.max(a,0))
print(torch.amax(a,0))
print(torch.argmax(a,0))
print(torch.maximum(a,b))
print(torch.eq(a,b))
c=torch.arange(1,7,1)
print(c)
print(torch.topk(c,5))
b=torch.tensor([-1.71,0.17,-0.05,-0.1])
print(torch.clamp(b,min=-1,max=0.1))

torch.return_types.max(
values=tensor([2, 4]),
indices=tensor([1, 1]))
tensor([2, 4])
tensor([1, 1])
tensor([[1, 3],
        [3, 4]])
tensor([[ True, False],
        [False,  True]])
tensor([1, 2, 3, 4, 5, 6])
torch.return_types.topk(
values=tensor([6, 5, 4, 3, 2]),
indices=tensor([5, 4, 3, 2, 1]))
tensor([-1.0000,  0.1000, -0.0500, -0.1000])


线性代数

In [16]:
a=torch.tensor([[1,3],[2,4]])
b=torch.rand(2,3,2)
print(b)
print(a.T)
print(torch.transpose(b,0,1))
print(torch.trace(a))
print(torch.matmul(a,a))   #矩阵乘法
print(torch.dot(a[1,:],a[0,:]))
print(torch.qr(a.float()))

tensor([[[0.0504, 0.7945],
         [0.4009, 0.4715],
         [0.9701, 0.4135]],

        [[0.6097, 0.8286],
         [0.9633, 0.3766],
         [0.2590, 0.0220]]])
tensor([[1, 2],
        [3, 4]])
tensor([[[0.0504, 0.7945],
         [0.6097, 0.8286]],

        [[0.4009, 0.4715],
         [0.9633, 0.3766]],

        [[0.9701, 0.4135],
         [0.2590, 0.0220]]])
tensor(5)
tensor([[ 7, 15],
        [10, 22]])
tensor(14)
torch.return_types.qr(
Q=tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]]),
R=tensor([[-2.2361, -4.9193],
        [ 0.0000, -0.8944]]))


张量的索引与提取

In [36]:
a=torch.tensor([[1,3],[2,4]])
b=torch.tensor([1,2,3,4])
print(a[0,0].item())     #只能提取标量的内容
print(torch.take(b,torch.tensor([1,3])))  #b将被看作一维
x=torch.rand(3,4)
print(x)
print(torch.index_select(x,0,torch.tensor([0,2])))
print(torch.index_select(x,1,torch.tensor([0,2])))
t = torch.tensor([[1, 2], [3, 4]])
print(torch.gather(t, 1, torch.tensor([[0,0], [1, 0]])))
print(torch.gather(t, 1, torch.tensor([[0, 0,0], [1, 0,0]])))
x=torch.rand(5)
print(x)
print(torch.masked_select(x,torch.tensor([True,True,False,False,True])))

1
tensor([2, 4])
tensor([[0.5291, 0.0588, 0.8209, 0.3188],
        [0.2909, 0.1093, 0.5630, 0.1545],
        [0.2750, 0.8830, 0.9339, 0.9807]])
tensor([[0.5291, 0.0588, 0.8209, 0.3188],
        [0.2750, 0.8830, 0.9339, 0.9807]])
tensor([[0.5291, 0.8209],
        [0.2909, 0.5630],
        [0.2750, 0.9339]])
tensor([[1, 1],
        [4, 3]])
tensor([[1, 1, 1],
        [4, 3, 3]])
tensor([0.5877, 0.0818, 0.9653, 0.9124, 0.1005])
tensor([0.5877, 0.0818, 0.1005])


（四）张量的拼拆与变形

改变形状

In [70]:
a=torch.rand(3,4)
print(a.shape)
a=a.view([2,2,3])
print(a.shape)
a=a.view(12)
print(a.shape)
a=a.view([4,-1])
print(a.shape)
print(torch.reshape(a,[3,4]))
print(a.size())
print(torch.reshape(a,[1,1,-1]))
print(torch.reshape(a,[-1,1,1]))
print(torch.reshape(a,[1,-1,1]))

torch.Size([3, 4])
torch.Size([2, 2, 3])
torch.Size([12])
torch.Size([4, 3])
tensor([[0.8550, 0.4121, 0.0643, 0.5459],
        [0.7993, 0.9838, 0.9265, 0.3651],
        [0.5090, 0.1634, 0.6606, 0.8551]])
torch.Size([4, 3])
tensor([[[0.8550, 0.4121, 0.0643, 0.5459, 0.7993, 0.9838, 0.9265, 0.3651,
          0.5090, 0.1634, 0.6606, 0.8551]]])
tensor([[[0.8550]],

        [[0.4121]],

        [[0.0643]],

        [[0.5459]],

        [[0.7993]],

        [[0.9838]],

        [[0.9265]],

        [[0.3651]],

        [[0.5090]],

        [[0.1634]],

        [[0.6606]],

        [[0.8551]]])
tensor([[[0.8550],
         [0.4121],
         [0.0643],
         [0.5459],
         [0.7993],
         [0.9838],
         [0.9265],
         [0.3651],
         [0.5090],
         [0.1634],
         [0.6606],
         [0.8551]]])


合并：stack会增加一个维度，cat不会

In [64]:
a=torch.rand(2,3)
print(a)
print(torch.cat((a,a,a),0))
print(torch.cat((a,a,a),1))
print(torch.stack((a,a,a),0))
print(torch.stack((a,a,a),1))
print(torch.stack((a,a,a),2))

tensor([[0.6902, 0.5274, 0.1256],
        [0.1883, 0.8033, 0.9867]])
tensor([[0.6902, 0.5274, 0.1256],
        [0.1883, 0.8033, 0.9867],
        [0.6902, 0.5274, 0.1256],
        [0.1883, 0.8033, 0.9867],
        [0.6902, 0.5274, 0.1256],
        [0.1883, 0.8033, 0.9867]])
tensor([[0.6902, 0.5274, 0.1256, 0.6902, 0.5274, 0.1256, 0.6902, 0.5274, 0.1256],
        [0.1883, 0.8033, 0.9867, 0.1883, 0.8033, 0.9867, 0.1883, 0.8033, 0.9867]])
tensor([[[0.6902, 0.5274, 0.1256],
         [0.1883, 0.8033, 0.9867]],

        [[0.6902, 0.5274, 0.1256],
         [0.1883, 0.8033, 0.9867]],

        [[0.6902, 0.5274, 0.1256],
         [0.1883, 0.8033, 0.9867]]])
tensor([[[0.6902, 0.5274, 0.1256],
         [0.6902, 0.5274, 0.1256],
         [0.6902, 0.5274, 0.1256]],

        [[0.1883, 0.8033, 0.9867],
         [0.1883, 0.8033, 0.9867],
         [0.1883, 0.8033, 0.9867]]])
tensor([[[0.6902, 0.6902, 0.6902],
         [0.5274, 0.5274, 0.5274],
         [0.1256, 0.1256, 0.1256]],

        [[0.1883, 0.1883

分块：chunk用于平均分块，第二个参数为平均分为几块，spilt不平均分，第二个参数向量表示每一块的行数；第三个参数均为分块维度。

In [78]:
a=torch.rand(4,3,4)
print(torch.chunk(a,2,0))
print(torch.chunk(a,2,1))
print(torch.chunk(a,3,2))
print(torch.split(a,[1,3],0))
print(torch.split(a,[1,2],1))

(tensor([[[0.7043, 0.6343, 0.3183, 0.1325],
         [0.8560, 0.5837, 0.7610, 0.5017],
         [0.0836, 0.1199, 0.6244, 0.4331]],

        [[0.3159, 0.5753, 0.1571, 0.7462],
         [0.4330, 0.7616, 0.3375, 0.2553],
         [0.4162, 0.1262, 0.4016, 0.1169]]]), tensor([[[0.1288, 0.9278, 0.9681, 0.4022],
         [0.2588, 0.1727, 0.5065, 0.4860],
         [0.4261, 0.2434, 0.5032, 0.9790]],

        [[0.9836, 0.0587, 0.5013, 0.2730],
         [0.7209, 0.9671, 0.6290, 0.7841],
         [0.4790, 0.7242, 0.1074, 0.9843]]]))
(tensor([[[0.7043, 0.6343, 0.3183, 0.1325],
         [0.8560, 0.5837, 0.7610, 0.5017]],

        [[0.3159, 0.5753, 0.1571, 0.7462],
         [0.4330, 0.7616, 0.3375, 0.2553]],

        [[0.1288, 0.9278, 0.9681, 0.4022],
         [0.2588, 0.1727, 0.5065, 0.4860]],

        [[0.9836, 0.0587, 0.5013, 0.2730],
         [0.7209, 0.9671, 0.6290, 0.7841]]]), tensor([[[0.0836, 0.1199, 0.6244, 0.4331]],

        [[0.4162, 0.1262, 0.4016, 0.1169]],

        [[0.4261, 0.2434, 0.5

维度

In [86]:
a=torch.rand(3,1,3,1,1)
print(torch.unbind(a,4))   #删除第四维度
b=torch.squeeze(a)      #删除全部多余维度
print(b)    
b=torch.unsqueeze(b,2)    #增添维度
print(b)  
print(torch.transpose(b,0,2))

(tensor([[[[0.3215],
          [0.2742],
          [0.2269]]],


        [[[0.9251],
          [0.2706],
          [0.7992]]],


        [[[0.1598],
          [0.2628],
          [0.8503]]]]),)
tensor([[0.3215, 0.2742, 0.2269],
        [0.9251, 0.2706, 0.7992],
        [0.1598, 0.2628, 0.8503]])
tensor([[[0.3215],
         [0.2742],
         [0.2269]],

        [[0.9251],
         [0.2706],
         [0.7992]],

        [[0.1598],
         [0.2628],
         [0.8503]]])
tensor([[[0.3215, 0.9251, 0.1598],
         [0.2742, 0.2706, 0.2628],
         [0.2269, 0.7992, 0.8503]]])


（五）激活函数

In [3]:
import torch.nn as nn
x=torch.tensor(range(-8,9))
x=x.float()
f1=nn.Threshold(-5,15)
print(f1(x))
f2=nn.ReLU()
print(f2(x))
f3=nn.ELU(1)
print(f3(x))
f4=nn.LeakyReLU(0.02)   #参数为泄露斜率，默认0.01
print(f4(x))
f5=nn.Sigmoid()
print(f5(x))
f6=nn.Tanh()
print(f6(x))
f7=nn.Hardtanh()    #取绝对值或平方可以当损失函数
print(f7(x))
f8=nn.Softmax(dim=0)
print(f8(x))
f9=nn.LogSoftmax(dim=0)
print(f9(x))
f10=nn.Softplus()
print(f10(x))
#MaxOut暂时没有实现，Github上可以找到

tensor([15., 15., 15., 15., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,
         6.,  7.,  8.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2., 3., 4., 5., 6., 7., 8.])
tensor([-0.9997, -0.9991, -0.9975, -0.9933, -0.9817, -0.9502, -0.8647, -0.6321,
         0.0000,  1.0000,  2.0000,  3.0000,  4.0000,  5.0000,  6.0000,  7.0000,
         8.0000])
tensor([-0.1600, -0.1400, -0.1200, -0.1000, -0.0800, -0.0600, -0.0400, -0.0200,
         0.0000,  1.0000,  2.0000,  3.0000,  4.0000,  5.0000,  6.0000,  7.0000,
         8.0000])
tensor([3.3535e-04, 9.1105e-04, 2.4726e-03, 6.6929e-03, 1.7986e-02, 4.7426e-02,
        1.1920e-01, 2.6894e-01, 5.0000e-01, 7.3106e-01, 8.8080e-01, 9.5257e-01,
        9.8201e-01, 9.9331e-01, 9.9753e-01, 9.9909e-01, 9.9966e-01])
tensor([-1.0000, -1.0000, -1.0000, -0.9999, -0.9993, -0.9951, -0.9640, -0.7616,
         0.0000,  0.7616,  0.9640,  0.9951,  0.9993,  0.9999,  1.0000,  1.0000,
         1.0000])
tensor([-1., -1., -1., -1., -1., -1., -1., -1.,  0.,  1., 

（六）损失函数

回归问题loss

In [4]:
x=torch.tensor(range(-8,9))
x=x.float()
y=x+torch.randn(17)
print(x)
print(y)
print(x-y)
print(torch.mean(torch.abs(x-y)))
print(torch.mean((x-y)**2))
los1=nn.L1Loss()
print(los1(x,y))
los2=nn.MSELoss()
print(los2(x,y))
los3=nn.SmoothL1Loss()
print(los3(x,y))
los4=nn.HuberLoss()
print(los4(x,y))

tensor([-8., -7., -6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,
         6.,  7.,  8.])
tensor([-8.3612, -6.1148, -5.6255, -6.3858, -5.1459, -3.2029, -3.2986, -1.2185,
        -0.1330,  0.8922,  2.3900,  2.1025,  3.4778,  5.8204,  5.3299,  6.9021,
         9.0232])
tensor([ 0.3612, -0.8852, -0.3745,  1.3858,  1.1459,  0.2029,  1.2986,  0.2185,
         0.1330,  0.1078, -0.3900,  0.8975,  0.5222, -0.8204,  0.6701,  0.0979,
        -1.0232])
tensor(0.6197)
tensor(0.5589)
tensor(0.6197)
tensor(0.5589)
tensor(0.2718)
tensor(0.2718)


多分类问题Loss

In [19]:
target=torch.empty(2, dtype=torch.long).random_(4)
y = torch.randn(2, 4)
print(target)
print(y)
los5 = nn.NLLLoss()  #要求input为每个分类概率的对数，NLLL求其的负对数和。
g1=nn.LogSoftmax(dim=1)
input=g1(y)
print(input)
print(los5(input,target))
los6=nn.CrossEntropyLoss()
print(los6(y,target))

tensor([0, 2])
tensor([[-0.9143, -0.0390, -0.4401,  0.7279],
        [ 0.6095, -0.4507, -0.8436,  0.4791]])
tensor([[-2.3198, -1.4444, -1.8455, -0.6775],
        [-0.8993, -1.9596, -2.3524, -1.0297]])
tensor(2.3361)
tensor(2.3361)


二分类Loss

In [29]:
target=torch.empty(3, dtype=torch.long).random_(2)
target=target.float()
y = torch.randn(3)
print(target)
print(y)
g2=nn.Sigmoid()
input=g2(y)
los7=nn.BCELoss()
print(los7(input,target))
los8=nn.BCEWithLogitsLoss()
print(los8(y,target))

tensor([1., 1., 0.])
tensor([-2.0321,  0.8872,  0.7734])
tensor(1.2176)
tensor(1.2177)


（七）导数

In [33]:
x = torch.ones(5)  
y = torch.zeros(3) 
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.1923, 0.2009, 0.1351],
        [0.1923, 0.2009, 0.1351],
        [0.1923, 0.2009, 0.1351],
        [0.1923, 0.2009, 0.1351],
        [0.1923, 0.2009, 0.1351]])
tensor([0.1923, 0.2009, 0.1351])


（八）优化器

In [58]:
import torch.optim as opt
y=torch.rand(3,requires_grad=True)
y=[y]
print(y)
loss=torch.mean(y[0]**2)
optimizer1=opt.SGD(y,lr=0.01,momentum=0.5)   #默认动量为0
optimizer2=opt.Adagrad(y, lr=0.01, lr_decay=0, weight_decay=0)
optimizer3=opt.RMSprop(y, lr=0.01, alpha=0.99, weight_decay=0, momentum=0)   #上两种实现了学习率的自我调整
optimizer4=opt.Adam(y, lr=0.01, betas=(0.9, 0.999), weight_decay=0)   #结合RMS与动量
#第三种与第四种效果较好且常用

opter_use=optimizer4
for i in range(1,100):
    opter_use.zero_grad()
    loss=torch.mean(y[0]**2)
    loss.backward()
    opter_use.step()
print(y)

[tensor([0.6422, 0.6436, 0.1657], requires_grad=True)]
[tensor([0.0249, 0.0254, 0.0007], requires_grad=True)]


（九）torchvision

In [3]:
import torchvision.datasets as datasets
import torchvision.transforms as transforms
from PIL import Image
tra=datasets.MNIST(root="data",train=True, download=True,transform=transforms.ToTensor())
tes=datasets.MNIST(root="data",train=False, download=True,transform=transforms.ToTensor())
ima=tra[0][0]
tran1=transforms.ToPILImage()
ima=tran1(ima)

In [15]:
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
tra_dloader = DataLoader(tra, batch_size=64, shuffle=True)
tes_dloader = DataLoader(tes, batch_size=64, shuffle=True)
tra_loader_use=iter(tra_dloader)
a,b=next(tra_loader_use)
print(b)
print(a.size())
a2=a.squeeze()
#print(a2[0])
#plt.plot(range(1,11),range(1,11))

tensor([2, 6, 5, 0, 6, 3, 3, 7, 8, 9, 2, 2, 5, 8, 1, 2, 9, 1, 6, 9, 8, 9, 8, 5,
        7, 1, 3, 2, 9, 2, 2, 1, 6, 0, 3, 1, 8, 5, 6, 9, 4, 4, 9, 8, 3, 8, 8, 5,
        2, 7, 6, 0, 9, 2, 3, 7, 9, 4, 8, 4, 9, 6, 2, 7])
torch.Size([64, 1, 28, 28])


（十）神经网络的创建与操作

In [8]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.func=nn.Linear(13,1)
    def forward(self,x):
        return self.func(x)

In [10]:
mod=Net()
for par in mod.parameters():
    print(par)

Parameter containing:
tensor([[-0.1688, -0.2329, -0.1872, -0.0004,  0.1975,  0.1643,  0.1799, -0.0496,
          0.2422, -0.1140, -0.0198,  0.0459,  0.0923]], requires_grad=True)
Parameter containing:
tensor([-0.0335], requires_grad=True)


In [12]:
for par in mod.named_parameters():
    print(par)

('func.weight', Parameter containing:
tensor([[-0.1688, -0.2329, -0.1872, -0.0004,  0.1975,  0.1643,  0.1799, -0.0496,
          0.2422, -0.1140, -0.0198,  0.0459,  0.0923]], requires_grad=True))
('func.bias', Parameter containing:
tensor([-0.0335], requires_grad=True))


（十一）神经网络层函数

In [2]:
input = torch.randn(32, 1, 5, 5)
m1 = nn.Conv2d(1, 32, 5, 1, 1)
m2 = nn.Flatten(1,3)
output = m1(input)
print(output.size())
output=m2(output)
print(output.size())

NameError: name 'torch' is not defined

In [3]:
model=nn.Sequential(nn.Linear(100,20),nn.ReLU(),nn.Linear(20,4))
input = torch.randn(45,100)
output=model(input)
print(output.size())

torch.Size([45, 4])


In [23]:
m1 = nn.Conv2d(16, 33, (3, 5))
m2 = nn.Conv2d(16, 33, (3, 5),stride=(2,1))
m3 = nn.Conv2d(16, 33, (3, 5),stride=(2,1),padding=(4,2))
m4 = nn.Conv2d(16, 33, (3, 5),stride=(2,1),padding=(4,2),dilation=(3,1))
input = torch.randn(20, 16, 50, 100)
output = m1(input)
print(output.shape)
output = m2(input)
print(output.shape)
output = m3(input)
print(output.shape)
output = m4(input)
print(output.shape)

torch.Size([20, 33, 48, 96])
torch.Size([20, 33, 24, 96])
torch.Size([20, 33, 28, 100])
torch.Size([20, 33, 26, 100])


In [25]:
m1 = nn.Conv2d(16, 33, (3, 5))
input = torch.randn(20,  50, 100)
output = m1(input)
print(output.shape)

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [33, 16, 3, 5], but got 3-dimensional input of size [20, 50, 100] instead